### ISSUE TITLE
Color preview won't work on hover anymore

### ISSUE THREAD

**Issue by soh3il-zz** [thedarkone/firepicker#24] opened 2012-08-14 01:40 UTC
I have the recent firefox & firebug.
when you hover your mouse over the color, it won't show you the preview of the color like before. you have to click on it to start editing to see the preview of the color.

but now it just show an empty circle, the preview of the color won't show up on hover. I believe it was working fine before the updates. not sure though ...

**Comment by thedarkone** [comment] 2012-08-14 11:57
I'm on OS X, beta Firefox 15.0, Firebug 1.10.2, Firepicker 1.4.1 and don't have this problem. What versions are you using?

**Comment by soh3il-zz** [comment] 2012-08-14 15:36
I'm on Os X Mountain Lion, Firefox 14.01, FireBug 1.10.2

**Comment by thedarkone** [comment] 2012-08-14 21:10
I was unable to reproduce with Firefox 14.01 as well :(.

Could you test, that the issues goes away if you uninstall Firepicker?

Maybe you're using some other addons that might be interfering with Firepicker?

**Comment by soh3il-zz** [comment] 2012-08-14 21:28
Now it works fine. It interfere with the "Friendly Bug" Plugin 

Thanx

**Comment by thedarkone** [comment] 2012-08-14 22:49
Alright, thanks and closing.

**Closed as completed by thedarkone** 2012-08-14 22:49 UTC
